name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.1-dev.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.12.0 <3.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.4.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http_parser: ^4.0.2
  http: ^0.13.6
  archive: ^3.3.7
  logging: ^1.1.1
  meta: ^1.9.1
  googleapis: ^11.0.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.1
  mime: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  collection: ^1.17.1
  shelf_cors_headers: ^0.1.4
dev_dependencies:
  test: ^1.18.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  shelf_router_generator: ^1.0.6
  chunked_stream: ^1.4.2
